### ISSUE TITLE
prevent removal of publication metadata

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods_capability_publishing#2]
Users should not be allowed to remove a publication metadata tag once applied.  The objects, collections, and published data sets will be immutable.

**Comment by jasoncoposky** [comment]
admins should have the ability to remove metadata for recovering from inappropriately applied metadata.

**Comment by trel** [comment]
should there be a check for when something is 're-published'?  either by accident or on purpose?  is that implementation-specific, depending on the endpoint destination/technology/platform?

**Comment by jasoncoposky** [comment]
republishing by mistake is handled by the publishing policy:
https://github.com/irods/irods_capability_publishing/blob/master/libirods_rule_engine_plugin-publishing.cpp#L213

**Comment by trel** [comment]
it's handled in the sense that it knows it was published before?     and so it doesn't reach back out to the endpoint again?

**Comment by jasoncoposky** [comment]
yes, if the metadata was already in place, no more work is done.

**Comment by trel** [comment]
i think this is complete - please close if so.

**Comment by trel** [comment]
confirmed.
